server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Supermarket?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: test/**
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 0


logging:
  level:
    com.sd: debug
  pattern:
    dateformat: HH:mm:ss


mybatis-plus:
  type-aliases-package: com.sd.model.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto


knife4j:
  enable: true
  openapi:
    title: "超时进销管理接口文档"
    description: "超时进销管理接口文档"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.sd.controller