server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Supermarket?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: test/**

logging:
  level:
    com.sd: debug
  pattern:
    dateformat: HH:mm:ss


mybatis-plus:
  type-aliases-package: com.sd.model.entity

